# Generated by Django 4.1.1 on 2023-07-13 14:55

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_grade'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Долгота'),
        ),
    ]
